# makemigrationsで作成されるマイグレーションファイル
# このファイルが最初の1つめ
# Generated by Django 5.1.7 on 2025-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('contents_text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
