services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/dockerfile/development/Dockerfile
      args:
        VITE_API_HOST_ADDRESS: http://localhost
    container_name: djangoblog_development_frontend
    ports:
      - "80:80"
    restart: always
    # volumes:
    #   - ./backend/static:/static  # ← これを追加 adminやapi/docs用cssを
    env_file:
      - .envs/development/frontend
    depends_on:
      - backend
  playwright-mock:
    build:
      context: .
      dockerfile: ./playwright-mock/dockerfile/local/Dockerfile
    container_name: djangoblog_development_playwright-mock
    profiles:
      - e2e-mock
    depends_on:
      - frontend
      - backend
    working_dir: /app
    env_file:
      - ./.envs/development/frontend
    volumes:
      - ./playwright-mock:/app  # ← playwright-mock の中の mocked_tests をマウント
  backend:
    build:
      context: .
      dockerfile: ./backend/dockerfile/development/Dockerfile
    image: djangoblog_development_backend_img
    container_name: djangoblog_development_backend
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.envs/development/django
      - ./.envs/development/frontend
      - ./.envs/development/postgres
    working_dir: /app
    volumes:
      - ./backend:/app
      # 以下はバックエンドディレクトリの外にあるpytestファイルを、コンテナのapp内に置かないとテストができないのでマウント
      # - ./pytest.ini:/app/pytest.ini
    # # development.ymlではフロントエンドのnginxを経る必要があるので、直接アクセスは不可にしました。開けた場合で、ブラウザからバックエンドにアクセスしたらcssの表示がくずれます。
    # ports:
    #   - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: djangoblog_development_postgres_img
    container_name: djangoblog_development_postgres
    restart: always
    env_file:
      - ./.envs/development/postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # user: "${UID:-1000}:${GID:-1000}" #<- postgresにはこれはかけない
    healthcheck:
      #ヘルスチェック(postgresが正常に動作しているかどうか)は以下のスクリプトを実行して行う
      # test: ["CMD", "/usr/local/bin/check-db.sh"]
      # スクリプトファイルではなく、直接コマンドを実行。ダブルドルにしておくのは、composeファイル内でのエスケープのため
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  db_data:
  node_modules:  # Vueプロジェクトの依存ファイルを保持するボリューム

#-------
#このdocker-compose.ymlを使う場合、フロントエンドのビルドのためのコマンドと、配信のためのコマンドを叩く必要がある。
# ビルド&配信 : docker compose -f development.yml up --build
# バックエンドのマイグレーション & スーパーユーザー作成 & 初期データ作成 : sh scripts/development/setup-scripts.sh